### ISSUE TITLE
Purge volumes for purge bucket

### ISSUE THREAD

**Issue by bynnek** [vintagepc/RPM-Post#3] opened 2020-01-22 05:51 UTC
It seems like the BB3D RPM wants specific "blob" sizes when it purges and folks just run the purge several time if they haven't extruded enough material.  As it stands right now (according to your readme file) it can over-purge into the bucket and get messed up correct?

Once your script calculates the purge volume it is going to purge, could it not round that up to a multiple of the standard blob size and run the purge / eject routine the correct amount of times to satisfy that?  I should just start reading your code, but are you pulling the purge values from: ;wiping_volumes_extruders &
; wiping_volumes_matrix
at the end of the gcode?

**Comment by vintagepc** [comment] 2020-01-22 12:15
Yes, and yes. 

The ideal purge blob size is 40mm³, correct? I'll address this very soon.

**Comment by vintagepc** [comment] 2020-01-23 02:56
I've just pushed up a fix for the purge segmentation; this should prevent overloading the mechanism. It should generate the correct number of 40 (linear) mm blobs to meet or exceed the specified purge volume.

**Comment by bynnek** [comment] 2020-01-26 23:21
Sorry, I haven't had a chance yet to try it.  I'll try in the next day or so.  Thanks for the quick update to the code!

**Comment by vintagepc** [comment] 2020-01-27 00:01
Not a problem! I tried it out myself just now and fixed two small bugs with fan timing and retraction. Seems to be working as intended, barring what I think are issues with my RPM setup.

**Comment by vintagepc** [comment] 2020-02-02 19:43
Closing, I've merged #3

**Closed by vintagepc** 2020-02-02 19:43 UTC
Labels: bug, testing

**Comment by bynnek** [comment] 2020-02-05 06:00
I finally got around to testing this.  Looks like it is working correctly.  Thanks!
